### ISSUE TITLE
Add link to issue tracker URL

### ISSUE THREAD

**Issue by graemerocher** [sheehan/grails3-plugins#17]
The github and bintray links are nice, would be good to have a link to the issue tracker

**Comment by bobbywarner** [comment]
Given that almost all plugins use GitHub Issues as the issue tracker, I actually think having another link is redundant since we already link to the repo.  Thoughts?

**Comment by sheehan** [comment]
There is one using bitbucket :)

I'm thinking about adding a sidebar to the plugin view similar to [this](https://www.npmjs.com/package/d-pac.functions) that would have more detail about versions, license, etc. That could be a good place for this link.

**Comment by graemerocher** [comment]
I like the sidebar idea
