### ISSUE TITLE
Cannot enter to many plugin's pages

### ISSUE THREAD

**Issue by alex-shamshurin** [sheehan/grails3-plugins#26]
When I click on plugin's name, browser redirects to a plugin's page which renders normally but in a second browser goes back to the list and location string is "/plugins.html#undefined". But it happens not all the time, may be in 80% cases.  I use chrome.

**Comment by sheehan** [comment]
Strange... I can't seem to reproduce. The site is embedded in an iframe on grails.org. Does the same happen if you go directly to http://sheehan.github.io/grails3-plugins/ ?

**Comment by salex772** [comment]
1. I've checked that and can confirm again the same on grails.org, if you interested in I can show it to you via hangouts video or skype. 

2. No, on that (original) site this error does not happen.

**Comment by sheehan** [comment]
Something with the iframe-to-parent message logic then maybe. Can you capture a screen cast?

**Comment by salex772** [comment]
No, I cannot, it happens during one second - video only. It happens on all my computers. Don't you really see this issue?

**Comment by sheehan** [comment]
No, it works ok for me http://recordit.co/BmJrTKM2ov

**Comment by sheehan** [comment]
The app is no longer in an iframe so this issue should be fixed now.
