### ISSUE TITLE
Click the GitHub Start button and page goes blank

### ISSUE THREAD

**Issue by sbglasius** [sheehan/grails3-plugins#28]
If I click the GitHub start button, the page goes blank, except from the page header. Same thing, if I click the GitHub Star button in the list of plugins.

Not sure, what is supposed to happen though.

**Comment by sheehan** [comment]
Looks to be frame-related. We're going to be moving away from the iframe approach in the near future and then this should be fixed.

**Comment by sheehan** [comment]
fixed now
