### ISSUE TITLE
investigate what other Bintray and github data could be useful to display in search results or detail

### ISSUE THREAD

**Issue by sheehan** [sheehan/grails3-plugins#4]

**Comment by ejaz-ahmed** [comment]
I think pulling stars and number of downloads will be a plus.

**Comment by sheehan** [comment]
I added github stars. The seem to be used a lot more than bintray stars. Still looking into other stats.

**Comment by sheehan** [comment]
> Statistics can only be retrieved for Premium accounts, and require a publish permission or higher.
